# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/setup/html-theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/og_rto.css" />
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD: <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&family=Inter:wght@400;600&family=Poppins:wght@600&display=swap" rel="stylesheet">
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="../images/favicon.ico">

#+ATTR_HTML: :class attc-logo
[[../index.org][file:../images/attc_logo.svg]]

#+ATTR_HTML: :class tab-navs
[[../guide/][Guide]] [[../docs/][Docs]] [[../api/][API]] [[https://github.com/uchicago-library/attachment-converter][file:../images/github.svg]] [[./index.html#table-of-contents][file:../images/navbar.svg]]

#+Author: Matt Teichman
#+Title: Docs | Attachment Converter

* Installation
Attachment Converter (=attc=) is available for Arch Linux, Ubuntu,
macOS, and Windows (via the Ubuntu WSL).  Please see below for
installation instructions.

** Windows
There is no native Windows version of =attc=, but we maintain a
version for Ubuntu version 26.04.  This allows you to run =attc= under
Ubuntu in your Windows Subsystem for Linux.

These instructions assume that you have Ubuntu WSL set up on your
Windows machine.  For a good guide to getting that set up, please
consult these resources:

+ https://ubuntu.com/wsl/docs/stable/howto/install-ubuntu-wsl2/
+ https://www.youtube.com/watch?v=9gT6vO_W6x0

After you finish setting your WSL up, it will log you into your new
Linux subsystem autoamtically.  You should see the prompt change color
into being green and blue.  Then, type this command and hit enter:

#+begin_example
  sudo add-apt-repository ppa:uchicago-dldc/attc
#+end_example

The purpose of this command is to make all of our [[https://uchicago-library.github.io/][Digital Library
Development Center]] software packages avaiable for you to install, and
it will prompt you for your WSL password.  (Note that as you type your
password, you won't see anything appear on the screen, but you should
assume your password is being typed, and hit enter when you're done.)
When you hit enter, if it's working, you should see a number of
messages go by, including something that looks like this:

#+begin_example
  URIs: https://ppa.launchpadcontent.net/uchicago-dldc/attc/ubuntu/
  Suites: resolute
  Components: main
  '
  More info: https://launchpad.net/~uchicago-dldc/+archive/ubuntu/attc
  Adding repository.
#+end_example

After you run that command, it will ask you to hit enter to continue.
Hit enter.  Next, you should see a series of messages about software
packages downloading.  Next, type this command:

#+begin_example
  sudo apt update
#+end_example

That command will check for updates.  Finally, to install =attc=, type
this command:

#+begin_example
  sudo apt install attc
#+end_example

It will print a long message telling you about all the Linux software
packages it's going to install, then ask you to confirm by typing =Y=
and hitting enter.  After you hit enter, you should see some more
messages get printed, and a progress bar on the bottom of the screen.
Installation should take about 2-5 minutes, depending on how fast your
computer and network connection are.

Congratulations!  =attc= is now installed to your WSL.  Please see our
[[../guide][Guide]] for instructions on how to use =attc=.  

** macOS

On macOS, we recommend installing =attc= via our
[[https://uchicago-library.github.io/][Digital Library Development
Center]] Homebrew tap.  If you don't have Hombrew installed on your
Mac, we recommend first doing these two things:

+ do a full macOS update
+ open a macOS Terminal and run the command =xcode-select --install=

With that out of the way, please see this website for instructions on
how to install Homebrew:

+ https://brew.sh/

With Homebrew set up, to install =attc=, please open your macOS
Terminal app and type this command:

#+begin_example
  brew tap uchicago-library/attc
#+end_example

That will subscribe you to our
[[https://uchicago-library.github.io/][Digital Library Development
Center]] Homebrew tap for =attc=, so that you can install it in one
command and easily get updates afterward.  Homebrew may print some
messages about how it is auto-updating when you run this command.
Next, please run:

#+begin_example
  brew trust uchicago-library/attc
#+end_example

This tells Homebrew that you trust our website for distributing the
application, and allows it to proceed with the install.  Next, type
this command to install =attc= to your Mac:

#+begin_example
  brew install attc
#+end_example

After you type the command, it will ask you to confirm.  Type =y= to
confirm.  You should see a lot of installation messages get printed to
the screen, and then at the end you'll see a message telling you to
run this command:

#+begin_example
  Attachment Converter depends on LibreOffice for some functionality.

  Please install it using:
    brew install --cask libreoffice
#+end_example

That last =brew install= command installs LibreOffice, which is what
Attachment Converter uses to convert =.doc= file attachments in email.

Congratulations!  =attc= is now installed on your Mac.  Please see our
[[../guide][Guide]] for instructions on how to use =attc=.

** Arch Linux

=attc= is not currently available via the AUR, but if you are using
Arch Linux and would like to install it, you can do so via our
[[https://uchicago-library.github.io/][DLDC]] Arch Linux software
repository.  First, add the following to your =/etc/pacman.conf=:

#+begin_example
  [dldc]
  SigLevel = Optional TrustAll
  Server = http://dldc.lib.uchicago.edu/open/repos/arch
#+end_example

Then refresh your package databases:

#+begin_example
  pacman -Syy
#+end_example

That will make =pacman= aware of our software repository.  When you
run the =-Syy=, =pacman= will ask you to confirm that you trust our
public key.  The key it displays should be this:

#+begin_example
  3EF45886DF1EF82B4782F5FBD331DB7453444E0E
#+end_example

Once you have confirmed that you would like to add our repository, you
can install =attc= in the usual way:

#+begin_example
  pacman -S attc
#+end_example

Congratulations!  =attc= is now installed on your Arch box.  Please
see our [[../guide][Guide]] for instructions on how to use =attc=.

* Advanced Installation Options

Although the above three options should work for most users on our
three supported platforms, power users may prefer to install =attc= in
other ways.

** =.deb= package

If you are on Ubuntu but our PPA doesn't suit your needs, for whatever
reason, you can find a =.deb= pacakge for =attc= [[https://dldc.lib.uchicago.edu/open/dist/attc/attc_0.2.12-1~resolute_amd64.deb][here]].  To download:

#+begin_example
  wget https://dldc.lib.uchicago.edu/open/dist/attc/attc_0.2.12-1~resolute_amd64.deb
#+end_example

To install:

#+begin_example
  apt install ./attc_0.2.12-1~resolute_amd64.deb
#+end_example

** Building From Source

*** Install =opam=

Attachment Converter is written in [[https://ocaml.org/][OCaml]], which means that in order to
build it, you need to install the =opam= package manager, which we
recommend doing via your operating system's package manager.  For
example:

Arch Linux:

#+begin_example
  $ pacman -S opam
#+end_example

macOS:

#+begin_example
  $ brew install opam
#+end_example

WSL Debian:

#+begin_example
  $ apt install opam
#+end_example

Then, regardless of how you install =opam=, you need to initialize it
in order to be able to use it.

#+begin_example
  $ opam init
  $ eval $(opam env)
#+end_example

=opam= should then print some information to the console telling you
about the steps it's taking to initialize.

That should be enough to get you going, but if you'd like more
detailed information on how to install =opam=, please see [[http://opam.ocaml.org/doc/Install.html#Using-your-distribution-39-s-package-system][the official
installation instructions]].


*** Install =opam= dependencies

To install all third-party library dependencies for Attachment
Converter to your =~/.opam= directory (which is where =opam= put the
OCaml compiler and other packages it's going to use when you ran =opam
init=), please run the following =make= rule from the root directory
of the GitHub project you cloned:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make deps
#+end_example

This will make the [[https://uchicago-library.github.io/][Digital Library Development Center]]'s very own
=opam= repository available to you, then install all of Attachment
Converter's third-party library dependencies.  =make deps= should
suffice for most purposes, but if you'd like to pursue the slightly
fancier option of creating a sandboxed =opam= switch, you can instead
run:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make sandbox
#+end_example

If you don't know what a sandboxed =opam= switch is, we suggest not
worrying about it and going with the =make deps= rule.

*** Install OS-level dependencies

Next, you must install Attachment Converter's OS-level dependencies.
For example:

Arch Linux:
#+begin_example
  $ pacman -S libreoffice pandoc libvips ghostscript poppler
#+end_example

macOS:
#+begin_example
  $ brew install libreoffice pandoc vips ghostscript verapdf poppler
#+end_example

WSL Debian:
#+begin_example
  $ apt install libreoffice pandoc vips ghostscript verapdf poppler-utils
#+end_example

*** Copy shell scripts to standard location

The shell scripts that Attachment Converter uses to invoke external
conversion utilities are expected to be located at one of several
specific filepaths.  If you install =attc= via a package manager, the
package manager will copy these shell scripts to whatever your host
OS's preferred path to executable artefacts is.  However, given that
this is a manual installation, the best option is to place them in
your home directory:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ mkdir -p ~/.config/attachment-converter/scripts
  $ cp conversion-scripts/*.sh ~/.config/attachment-converter/scripts
#+end_example

*** Time to Build

You should now be ready to build Attachment Converter.  To build:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make
#+end_example

You can then install Attachment Converter by copying the binary to
wherever you keep your binaries:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ install -m 755 _build/default/main.exe /path/to/your/binaries/attc
#+end_example

#+ATTR_HTML: :id back-to-top
[[./index.html][file:../images/back_to_top.svg]]
