# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/setup/html-theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/og_rto.css" />
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD: <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&family=Inter:wght@400;600&family=Poppins:wght@600&display=swap" rel="stylesheet">
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="../images/favicon.ico">

#+ATTR_HTML: :class attc-logo
[[../index.org][file:../images/attc_logo.svg]]

#+ATTR_HTML: :class tab-navs
[[../guide/][Guide]] [[../docs/][Docs]] [[../api/][API]] [[https://github.com/uchicago-library/attachment-converter][file:../images/github.svg]] [[./index.html#table-of-contents][file:../images/navbar.svg]]

#+Author: Matt Teichman
#+Title: Docs | Attachment Converter

* Installation
** Windows
There is no native Windows version of =attc=, but we maintain a
version for Ubuntu 26.04.  To install =attc= via the Ubuntu WSL on
your Windows machine:

*[ insert instructions for installing WSL here ]*

To install, please open up a fresh WSL terminal and type this command.

#+begin_example
  sudo add-apt-repository ppa:uchicago-dldc/attc
#+end_example

It will prompt you for your WSL password.  The window won't display
your password when you type it.  When you hit enter, if it's working,
you should see something like this in the console:

#+begin_example
  URIs: https://ppa.launchpadcontent.net/uchicago-dldc/attc/ubuntu/
  Suites: resolute
  Components: main
  '
  More info: https://launchpad.net/~uchicago-dldc/+archive/ubuntu/attc
  Adding repository.
#+end_example

And then after that, you should see a bunch of messages about things
downloading.  Next, type this command:

#+begin_example
  sudo apt update
#+end_example

That command will check for updates.  Finally, to install =attc=, type
this command:

#+begin_example
  sudo apt install attc
#+end_example

It will print a long message telling you about all the Linux
dependencies it's going to install, then ask you to confirm by typing
=Y= and hitting enter.

Congratulations.  =attc= is now installed to your WSL.  Please see our

[[../guide][Guide]] for instructions on how to use =attc=.

** macOS

On macOS, we recommend installing =attc= via Homebrew.  

*[ insert instructions for installing homebrew here ]*

*[ insert *instructions for dealing with XCode's nonsense + a reminder
to do a *system update if you haven't done one recently ]*

To install,
please open your Terminal app and type this command:

#+begin_example
  brew tap uchicago-library/attc
#+end_example

This will subscribe you to our UChicago Homebrew package for =attc=,
so that you can automatically get updates.  Homebrew may print some
messages about how it is auto-updating when you run this command.
Next, please run:

#+begin_example
  brew trust uchicago-library/attc
#+end_example

This tells Homebrew that you trust our repository, and allows it to go
ahead with the install.  Next, type this command to install =attc= to
your Mac:

#+begin_example
  brew install attc
#+end_example

After you type the command, it will ask you to confirm.  Type =y= to
confirm.  You should see a lot of installation messages get printed to
the screen, and then at the end you'll see a message telling you to
run this command:

#+begin_example
  Attachment Converter depends on LibreOffice for some functionality.

  Please install it using:
    brew install --cask libreoffice
#+end_example

This command installs LibreOffice, which is what Attachment Converter
uses to convert =.doc= file attachments in email.

* Installation <<install>>

Once this software is ready for official release, we will be providing
multiple installation options across as many hardware and OS platforms
as we can.  Currently, however, the only way to install the project is
to build it from source, which you probably only realistically want to
attempt if you're either a developer or a system administrator.  These
instructions are currently undergoing heavy revision, so if you try
them out and experience any difficulties, please don't hesitate to
contact us.  User feedback at this stage is incredibly valuable.

For ordinary users, we intend to make Attachment Converter available
to install via one of the standard package managers and also directly
as a binary upon its first release.  Please check back later this year
for updates!

As we work toward our first release, here are instructions for
building Attachment Converter from source and then installing it.

We have two available installation methods: an automated process
using a =GNUmakefile= and a manual process. Either method will
require you to download the source code.

You can get the latest source straight from our [[https://github.com/uchicago-library/attachment-converter][GitHub repository]]:

#+begin_example
  $ cd /path/to/your/source/code
  $ git clone https://github.com/uchicago-library/attachment-converter.git
#+end_example

** Automated Installation

Once you have finished downloading the source code, run:

#+begin_example
  $ make home-install
#+end_example

At the end of the installation process, you will see a notice saying:

#+begin_example
  Attachment Converter has been installed to ~/bin/attc.
  Please ensure that ~/bin is on your path.
#+end_example

You can ensure that the installation worked as intended by the following command.

MacOS:

#+begin_example
  $ echo "export PATH=~/bin:$PATH" >> ~/.zshrc
#+end_example

WSL Debian & Arch Linux:

#+begin_example
  $ echo "export PATH=~/bin:$PATH" >> ~/.bashrc
#+end_example

** Manual Building

*** Install =opam=

Attachment Converter is written in [[https://ocaml.org/][OCaml]], which means that in order to
build it, you need to install the =opam= package manager, which we
recommend doing via your operating system's package manager.  For
example:

Arch Linux:

#+begin_example
  $ pacman -S opam
#+end_example

macOS:

#+begin_example
  $ brew install opam
#+end_example

WSL Debian:

#+begin_example
  $ apt install opam
#+end_example

Then, regardless of how you install =opam=, you need to initialize it
in order to be able to use it.

#+begin_example
  $ opam init
  $ eval $(opam env)
#+end_example

=opam= should then print some information to the console telling you
about the steps it's taking to initialize.

That should be enough to get you going, but if you'd like more
detailed information on how to install =opam=, please see [[http://opam.ocaml.org/doc/Install.html#Using-your-distribution-39-s-package-system][the official
installation instructions]].

*** Install Mercurial

Attachment Converter relies on the Mercurial version control system to
install some of its third-party library dependencies.  For example:

Arch Linux:

#+begin_example
  $ pacman -S mercurial
#+end_example

macOS:

#+begin_example
  $ brew install mercurial
#+end_example

WSL Debian:

#+begin_example
  $ apt install mercurial
#+end_example

*** Install =opam= dependencies

To install all third-party library dependencies for Attachment
Converter to your =~/.opam= directory (which is where =opam= put the
OCaml compiler and other packages it's going to use when you ran =opam
init=), please run the following =make= rule from the root directory
of the GitHub project you cloned:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make deps
#+end_example

This will make the Digital Library Development Center's very own
=opam= repository available to you, then install all of Attachment
Converter's third-party library dependencies.  =make deps= should
suffice for most purposes, but if you'd like to pursue the slightly
fancier option of creating a sandboxed =opam= switch, you can instead
run:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make sandbox
#+end_example

If you don't know what a sandboxed =opam= switch is, we suggest not
worrying about it and going with the =make deps= rule.

*** Install OS-level dependencies

Next, you must install Attachment Converter's OS-level dependencies.
For example:

Arch Linux:
#+begin_example
  $ pacman -S libreoffice pandoc libvips ghostscript
#+end_example

macOS:
#+begin_example
  $ brew install libreoffice pandoc vips ghostscript verapdf
#+end_example

WSL Debian:
#+begin_example
  $ apt install libreoffice pandoc vips ghostscript verapdf
#+end_example

Finally, Attachment Converter has one OS-level dependency that is not
available through the standard repositories, called [[https://github.com/matteosecli/pdf2archive][=pdf2archive=]].
This is a utility for converting PDF to PDF-A-1b.

Download =pdf2archive=:

#+begin_example
  $ cd /path/to/your/source/code
  $ git clone git@github.com:matteosecli/pdf2archive.git
  $ cd pdf2archive
  $ chmod +x ./pdf2archive
  $ export PATH=$PATH:/path/to/your/source/code/pdf2archive
#+end_example

*** Copy shell scripts to standard location

In our current pre-alpha stage, the shell scripts that Attachment
Converter uses to invoke external conversion utilities are expected to
be located at a specific filepath.  This is expected to change soon as
we flesh out our installation story.  For this next step, please copy
them to that location:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ mkdir -p ~/.config/attachment-converter/scripts
  $ cp conversion-scripts/*.sh ~/.config/attachment-converter/scripts
#+end_example

*** Time to Build

You should now be ready to build Attachment Converter.  To build:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make
#+end_example

You can then install Attachment Converter by copying the binary to
wherever you keep your binaries:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ mv _build/default/main.exe /path/to/your/binaries/attc
#+end_example

* Advanced Concepts

** Conversion Customization

Coming soon...

#+ATTR_HTML: :id back-to-top
[[./index.html][file:../images/back_to_top.svg]]
