# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/og_rto.css" />
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD: <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&family=Inter:wght@400;600&family=Poppins:wght@600&display=swap" rel="stylesheet">
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="../images/favicon.ico">

#+ATTR_HTML: :class attc-logo
[[../index.org][file:../images/attc_logo.svg]]

#+ATTR_HTML: :class tab-navs
[[../guide/][Guide]] [[../docs/][Docs]] [[../api/][API]] [[https://github.com/uchicago-library/attachment-converter][file:../images/github.svg]] [[./index.html#table-of-contents][file:../images/navbar.svg]]

#+Author: Matt Teichman
#+Title: Docs | Attachment Converter

* Installation <<install>>

Once this software is ready for official release, we will be providing
multiple installation options across as many hardware and OS platforms
as we can.  Currently, however, the only way to install the project is
to build it from source, which you probably only realistically want to
attempt if you're either a developer or a system administrator.  These
instructions are currently undergoing heavy revision, so if you try
them out and experience any difficulties, please don't hesitate to
contact us.  User feedback at this stage is incredibly valuable.

For ordinary users, we intend to make Attachment Converter available
to install via one of the standard package managers and also directly
as a binary upon its first release.  Please check back later this year
for updates!

As we work toward our first release, here are instructions for
building Attachment Converter from source and then installing it.

We have two available installation methods: an automated process
using a =GNUmakefile= and a manual process. Either method will
require you to download the source code.

You can get the latest source straight from our [[https://github.com/uchicago-library/attachment-converter][GitHub repository]]:

#+begin_example
  $ cd /path/to/your/source/code
  $ git clone https://github.com/uchicago-library/attachment-converter.git
#+end_example

** Automated Installation

Once you have finished downloading the source code, run:

#+begin_example
  $ make home-install
#+end_example

At the end of the installation process, you will see a notice saying:

#+begin_example
  Attachment Converter has been installed to ~/bin/attc.
  Please ensure that ~/bin is on your path.
#+end_example

You can ensure that the installation worked as intended by the following command.

MacOS:

#+begin_example
  $ echo "export PATH=~/bin:$PATH" >> ~/.zshrc
#+end_example

WSL Debian & Arch Linux:

#+begin_example
  $ echo "export PATH=~/bin:$PATH" >> ~/.bashrc
#+end_example

** Manual Building

*** Install =opam=

Attachment Converter is written in [[https://ocaml.org/][OCaml]], which means that in order to
build it, you need to install the =opam= package manager, which we
recommend doing via your operating system's package manager.  For
example:

Arch Linux:

#+begin_example
  $ pacman -S opam
#+end_example

macOS:

#+begin_example
  $ brew install opam
#+end_example

WSL Debian:

#+begin_example
  $ apt install opam
#+end_example

Then, regardless of how you install =opam=, you need to initialize it
in order to be able to use it.

#+begin_example
  $ opam init
  $ eval $(opam env)
#+end_example

=opam= should then print some information to the console telling you
about the steps it's taking to initialize.

That should be enough to get you going, but if you'd like more
detailed information on how to install =opam=, please see [[http://opam.ocaml.org/doc/Install.html#Using-your-distribution-39-s-package-system][the official
installation instructions]].

*** Install Mercurial

Attachment Converter relies on the Mercurial version control system to
install some of its third-party library dependencies.  For example:

Arch Linux:

#+begin_example
  $ pacman -S mercurial
#+end_example

macOS:

#+begin_example
  $ brew install mercurial
#+end_example

WSL Debian:

#+begin_example
  $ apt install mercurial
#+end_example

*** Install =opam= dependencies

To install all third-party library dependencies for Attachment
Converter to your =~/.opam= directory (which is where =opam= put the
OCaml compiler and other packages it's going to use when you ran =opam
init=), please run the following =make= rule from the root directory
of the GitHub project you cloned:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make deps
#+end_example

This will make the Digital Library Development Center's very own
=opam= repository available to you, then install all of Attachment
Converter's third-party library dependencies.  =make deps= should
suffice for most purposes, but if you'd like to pursue the slightly
fancier option of creating a sandboxed =opam= switch, you can instead
run:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make sandbox
#+end_example

If you don't know what a sandboxed =opam= switch is, we suggest not
worrying about it and going with the =make deps= rule.

*** Install OS-level dependencies

Next, you must install Attachment Converter's OS-level dependencies.
For example:

Arch Linux:
#+begin_example
  $ pacman -S libreoffice pandoc libvips ghostscript
#+end_example

macOS:
#+begin_example
  $ brew install libreoffice pandoc vips ghostscript verapdf
#+end_example

WSL Debian:
#+begin_example
  $ apt install libreoffice pandoc vips ghostscript verapdf
#+end_example

Finally, Attachment Converter has one OS-level dependency that is not
available through the standard repositories, called [[https://github.com/matteosecli/pdf2archive][=pdf2archive=]].
This is a utility for converting PDF to PDF-A-1b.

Download =pdf2archive=:

#+begin_example
  $ cd /path/to/your/source/code
  $ git clone git@github.com:matteosecli/pdf2archive.git
  $ cd pdf2archive
  $ chmod +x ./pdf2archive
  $ export PATH=$PATH:/path/to/your/source/code/pdf2archive
#+end_example

*** Copy shell scripts to standard location

In our current pre-alpha stage, the shell scripts that Attachment
Converter uses to invoke external conversion utilities are expected to
be located at a specific filepath.  This is expected to change soon as
we flesh out our installation story.  For this next step, please copy
them to that location:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ mkdir -p ~/.config/attachment-converter/scripts
  $ cp conversion-scripts/*.sh ~/.config/attachment-converter/scripts
#+end_example

*** Time to Build

You should now be ready to build Attachment Converter.  To build:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ make
#+end_example

You can then install Attachment Converter by copying the binary to
wherever you keep your binaries:

#+begin_example
  $ cd /path/to/your/source/code/attachment-converter
  $ mv _build/default/main.exe /path/to/your/binaries/attc
#+end_example

* Advanced Concepts

** Conversion Customization

Coming soon...

#+ATTR_HTML: :id back-to-top
[[./index.html][file:../images/back_to_top.svg]]
